### ISSUE TITLE
Day 11 Lab - Missing technical requirements

### ISSUE THREAD

**Issue by elaewin** [luayghazwan/PicFeed#4]
You're still missing the following technical requirements:

* Layout an `imageView` in the center of the screen using Auto Layout and **give it a placeholder image**.

* The placeholder image should be added to the asset catalog and should have all appropriate sizes added(1x,2x,3x).

* In the attributes inspector, make sure to enable _Clips to Bounds_ and set the content mode to _Aspect Fill_ on the `imageView`.

* `UIImageView` Auto Layout Constraints:

  * width 0.75
  * height 0.75

**Comment by luyounus** [comment]
Thank you Erica! I fixed this issue. I will keep my Auto Layout Constraints to 100%. I don't like them sat to 75%.
